services:
  votx_db:
    image: postgres
    container_name: votx_db
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - path: "./db.env"
        required: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  votx:
    container_name: votx
    build: .
    ports:
      - 127.0.0.1:8008:8008
    env_file:
      - path: "./db.env"
        required: true
      - path: "./.env"
        required: true
    restart: always
    depends_on:
      votx_db:
        condition: service_healthy
        restart: true
        
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password

